/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.util;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author edisoncor
 */
public class PanelEstadisticas extends javax.swing.JPanel {

    private List<Coordenada> coordenadaList;
    
    /**
     * Creates new form PanelEstadisticas
     */
    public PanelEstadisticas() {
        initComponents();
        coordenadaList = new LinkedList<>();
        coordenadaList.add(new Coordenada(10, 10));
        coordenadaList.add(new Coordenada(11, 20));
        coordenadaList.add(new Coordenada(12, 5));
        coordenadaList.add(new Coordenada(13, 50));
        coordenadaList.add(new Coordenada(14, 2));
        coordenadaList.add(new Coordenada(15, 60));
        coordenadaList.add(new Coordenada(16, 70));
        coordenadaList.add(new Coordenada(17, 80));
        coordenadaList.add(new Coordenada(18, 50));
        coordenadaList.add(new Coordenada(19, 10));
        coordenadaList.add(new Coordenada(20, 30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) {
       Graphics2D g2 =(Graphics2D) g;
       dibujarEjes(g2);
        dibujaCoordenadas(g2);
       g2.dispose();
    }

    private void dibujarEjes(Graphics2D g2){
        g2.drawLine(0, 0, 0, getHeight()-5);
        g2.drawLine(0, getHeight()-5, getWidth(), getHeight()-5);
        g2.setColor(Color.RED);
    }
    
    private void dibujaCoordenadas(Graphics2D g2){
        Coordenada origen = new Coordenada(0, 0);
        for (Coordenada coordenada : coordenadaList) {
            g2.fillOval((coordenada.getX()*10)-3, getHeight()-8-coordenada.getY(), 6, 6);
            g2.drawLine(origen.getX()*10, getHeight()-5-origen.getY(), coordenada.getX()*10, getHeight()-5-coordenada.getY());
            origen = coordenada;
        }
    }

    public PanelEstadisticas(List<Coordenada> coordenadaList) {
        this.coordenadaList = coordenadaList;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
